# Generated by Django 6.1 on 2026-09-02 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon_name", models.CharField(default="shield", max_length=50)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trial_start_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_subscribed", models.BooleanField(default=False)),
                ("subscription_date", models.DateTimeField(blank=True, null=True)),
                ("current_week", models.IntegerField(default=1)),
                (
                    "github_pat",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "github_repo",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserWeekProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("is_unlocked", models.BooleanField(default=False)),
                ("lab_a_completed", models.BooleanField(default=False)),
                ("lab_b_completed", models.BooleanField(default=False)),
                (
                    "lab_b_flag_submitted",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("report_submitted", models.TextField(blank=True, default="")),
                ("report_score", models.IntegerField(default=0)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "week_number")},
            },
        ),
    ]
