# Generated by Django 6.1 on 2026-09-03 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_day",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_completed_day_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_completed_days",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserDailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("day_number", models.IntegerField()),
                ("global_day_number", models.IntegerField()),
                ("is_unlocked", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "flag_submitted",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("quiz_score", models.IntegerField(default=0)),
                ("report_submitted", models.TextField(blank=True, default="")),
                ("report_score", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["global_day_number"],
                "unique_together": {("user", "global_day_number")},
            },
        ),
    ]
