# Generated by Django 6.1 on 2026-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_current_day_userprofile_current_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="student_github_profile_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_linkedin_profile_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
