import React, { useState } from "react";
import { GitHubSettings } from "../hooks/useLMSState";
import { Github, Settings, CheckCircle2, AlertCircle, Share2, Copy, ArrowUpRight, Terminal, RefreshCw, Linkedin, Sparkles } from "lucide-react";

interface SocialIntegratorProps {
  lessonTitle: string;
  scriptContent: string;
  gitHubSettings: GitHubSettings;
  onUpdateGitHub: (updater: Partial<GitHubSettings>) => void;
  onMarkCommitted: () => void;
}

export const SocialIntegrator: React.FC<SocialIntegratorProps> = ({
  lessonTitle,
  scriptContent,
  gitHubSettings,
  onUpdateGitHub,
  onMarkCommitted
}) => {
  const [showConfig, setShowConfig] = useState(!gitHubSettings.token);
  const [patInput, setPatInput] = useState(gitHubSettings.token);
  const [usernameInput, setUsernameInput] = useState(gitHubSettings.username);
  const [repoInput, setRepoInput] = useState(gitHubSettings.repo || "my-bug-bounty-arsenal-2026");

  // Status & Logs
  const [actionStatus, setActionStatus] = useState({ text: "", isError: false });
  const [isProcessing, setIsProcessing] = useState(false);
  const [terminalLogs, setTerminalLogs] = useState<string[]>([]);

  // Open Modal/Public Ledger Details
  const [showLedgerModal, setShowLedgerModal] = useState(false);

  // Dynamic AI Markdown Summary explaining daily achievement
  const mdSummary = `### 🎯 BUG BOUNTY MASTERY - DAILY RESEARCH LOG\n` +
    `**Module Completed:** ${lessonTitle}\n` +
    `**Date Completed:** ${new Date().toLocaleDateString()}\n\n` +
    `#### 💡 What Was Achieved Today:\n` +
    `- **Code Audit:** Evaluated source code parameter handling and security boundaries.\n` +
    `- **Vulnerability Vector:** Isolated root cause logic flaw and crafted an exploit payload.\n` +
    `- **Automation:** Developed a standalone Python/Bash automation script to reproduce the exploit.\n` +
    `- **Verification:** Executed the attack in a local container sandbox and extracted the flag.\n\n` +
    `#### 🛠️ Exploit Script Code:\n` +
    `\`\`\`python\n` +
    `${scriptContent}\n` +
    `\`\`\`\n\n` +
    `*Automated research documentation generated by Bug Bounty Mastery.*`;

  const handleSaveSettings = () => {
    onUpdateGitHub({
      token: patInput.trim(),
      username: usernameInput.trim(),
      repo: repoInput.trim() || "my-bug-bounty-arsenal-2026"
    });
    setShowConfig(false);
    setActionStatus({ text: "GitHub credentials & custom repository updated locally.", isError: false });
  };

  const addLog = (log: string) => {
    setTerminalLogs((prev) => [...prev, log]);
  };

  // Real GitHub API Integration pushing to the user's custom repository
  const handlePushToGitHub = async () => {
    const targetRepo = repoInput.trim() || gitHubSettings.repo || "my-bug-bounty-arsenal-2026";
    const targetUser = usernameInput.trim() || gitHubSettings.username;
    const targetToken = patInput.trim() || gitHubSettings.token;

    if (!targetToken || !targetUser) {
      setShowConfig(true);
      setActionStatus({ text: "Please enter your GitHub Username and Personal Access Token.", isError: true });
      return;
    }

    setIsProcessing(true);
    setTerminalLogs(["[*] Connecting to GitHub REST API..."]);

    const fileName = `${lessonTitle.replace(/[\s&()\-]/g, "-").toLowerCase()}.py`;
    const path = `scripts/${fileName}`;
    const message = `docs: push exploit script for ${lessonTitle}`;
    const contentEncoded = btoa(unescape(encodeURIComponent(scriptContent)));

    try {
      // 1. Check if repo exists
      addLog(`[*] Verifying custom repository: ${targetUser}/${targetRepo}`);
      const repoRes = await fetch(`https://api.github.com/repos/${targetUser}/${targetRepo}`, {
        headers: {
          Authorization: `token ${targetToken}`,
          Accept: "application/vnd.github.v3+json"
        }
      });

      if (repoRes.status === 404) {
        addLog(`[!] Repository '${targetRepo}' not found. Creating new public repository...`);
        const createRes = await fetch(`https://api.github.com/user/repos`, {
          method: "POST",
          headers: {
            Authorization: `token ${targetToken}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json"
          },
          body: JSON.stringify({
            name: targetRepo,
            private: false,
            description: "Custom Bug Bounty Toolset & Exploit Scripts engineered in Bug Bounty Mastery"
          })
        });

        if (createRes.status === 201) {
          addLog(`[+] Successfully created repository: ${targetRepo}`);
        } else {
          throw new Error("Failed to create custom repository.");
        }
      } else {
        addLog(`[+] Validated active repository: ${targetRepo}`);
      }

      // 2. Try fetching existing file SHA
      addLog(`[*] Checking for existing files at: ${path}`);
      let fileSha = "";
      const fileRes = await fetch(`https://api.github.com/repos/${targetUser}/${targetRepo}/contents/${path}`, {
        headers: {
          Authorization: `token ${targetToken}`,
          Accept: "application/vnd.github.v3+json"
        }
      });

      if (fileRes.status === 200) {
        const fileData = await fileRes.json();
        fileSha = fileData.sha;
        addLog(`[*] Existing file found. Preparing commit revision...`);
      } else {
        addLog(`[*] Preparing initial file commit...`);
      }

      // 3. Write/Update file content
      const pushRes = await fetch(`https://api.github.com/repos/${targetUser}/${targetRepo}/contents/${path}`, {
        method: "PUT",
        headers: {
          Authorization: `token ${targetToken}`,
          "Content-Type": "application/json",
          Accept: "application/vnd.github.v3+json"
        },
        body: JSON.stringify({
          message,
          content: contentEncoded,
          sha: fileSha || undefined
        })
      });

      if (pushRes.status === 200 || pushRes.status === 201) {
        addLog(`[+] SCRIPT COMMITTED SUCCESSFULLY TO ${targetRepo}!`);
        setActionStatus({ text: `Exploit script committed to https://github.com/${targetUser}/${targetRepo}!`, isError: false });
        onMarkCommitted();
      } else {
        const errData = await pushRes.json();
        throw new Error(errData.message || "Push failed.");
      }

    } catch (err: any) {
      addLog(`[-] Error: ${err.message || err}`);
      setActionStatus({ text: `GitHub push failed: ${err.message || err}`, isError: true });
    } finally {
      setIsProcessing(false);
    }
  };

  // LinkedIn Sharing URL with AI-generated text
  const handleLinkedInShare = () => {
    const postText = `🎯 Bug Bounty Achievement Log:\nToday I analyzed and automated an exploit for "${lessonTitle}".\n\nI reverse-engineered the developer mindset, crafted an exploit payload, and committed my script to GitHub!\n\n#bugbounty #cybersecurity #infosec #ethicalhacking`;
    navigator.clipboard.writeText(postText);

    const targetRepo = repoInput.trim() || gitHubSettings.repo || "my-bug-bounty-arsenal-2026";
    const targetUser = usernameInput.trim() || gitHubSettings.username || "github-user";
    const repoUrl = `https://github.com/${targetUser}/${targetRepo}`;

    const shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(repoUrl)}`;
    window.open(shareUrl, "_blank");

    setActionStatus({ text: "AI achievement summary copied to clipboard! Opening LinkedIn share portal...", isError: false });
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(mdSummary);
    setActionStatus({ text: "AI Markdown research log copied to clipboard!", isError: false });
  };

  return (
    <div className="bg-hacker-card border border-hacker-border rounded-xl p-5 shadow-lg flex flex-col gap-4">

      {/* Title */}
      <div className="flex justify-between items-center border-b border-hacker-border pb-3">
        <h3 className="font-bold text-white flex items-center gap-2 font-mono text-xs">
          <Github size={18} className="text-white" /> AI RESEARCH LOG & GITHUB REPOSITORY PUSH
        </h3>
        <button
          onClick={() => setShowConfig(!showConfig)}
          className="text-xs text-hacker-amber hover:text-white flex items-center gap-1 font-mono"
        >
          <Settings size={13} /> [Configure GitHub Credentials]
        </button>
      </div>

      {/* GitHub Setup Card with Custom Repository Name per User */}
      {showConfig && (
        <div className="bg-hacker-dark border border-hacker-border/70 p-4 rounded-lg flex flex-col gap-3">
          <div className="text-xs font-mono font-bold text-hacker-amber flex items-center gap-1.5">
            <Sparkles size={14} /> LINK YOUR GITHUB ACCOUNT & CUSTOM REPOSITORY NAME
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="flex flex-col gap-1">
              <label className="text-[10px] text-hacker-muted font-mono uppercase">Personal Access Token (PAT)</label>
              <input
                type="password"
                value={patInput}
                onChange={(e) => setPatInput(e.target.value)}
                placeholder="ghp_..."
                className="bg-hacker-card border border-hacker-border rounded px-2.5 py-1 text-xs text-white font-mono focus:outline-none focus:ring-1 focus:ring-hacker-amber"
              />
            </div>

            <div className="flex flex-col gap-1">
              <label className="text-[10px] text-hacker-muted font-mono uppercase">GitHub Username</label>
              <input
                type="text"
                value={usernameInput}
                onChange={(e) => setUsernameInput(e.target.value)}
                placeholder="e.g. octocat"
                className="bg-hacker-card border border-hacker-border rounded px-2.5 py-1 text-xs text-white font-mono focus:outline-none focus:ring-1 focus:ring-hacker-amber"
              />
            </div>

            <div className="flex flex-col gap-1">
              <label className="text-[10px] text-hacker-muted font-mono uppercase">Custom Repository Name</label>
              <input
                type="text"
                value={repoInput}
                onChange={(e) => setRepoInput(e.target.value)}
                placeholder="my-bounty-arsenal-2026"
                className="bg-hacker-card border border-hacker-border rounded px-2.5 py-1 text-xs text-white font-mono focus:outline-none focus:ring-1 focus:ring-hacker-amber"
              />
            </div>
          </div>

          <div className="flex justify-between items-center mt-1">
            <p className="text-[9px] text-hacker-muted max-w-[70%]">
              Name your repository anything you want. The app will automatically create the repository if it doesn't exist and commit your daily exploit script into it.
            </p>
            <button
              onClick={handleSaveSettings}
              className="bg-hacker-amber hover:bg-amber-400 text-black font-bold px-4 py-1.5 rounded text-xs font-mono transition-all"
            >
              Save Credentials
            </button>
          </div>
        </div>
      )}

      {/* Primary Integration Buttons */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={() => setShowLedgerModal(true)}
          className="flex-1 bg-hacker-dark hover:bg-hacker-border border border-hacker-border text-white hover:text-hacker-green font-bold py-2.5 rounded-lg text-xs font-mono flex items-center justify-center gap-2 transition-all shadow-md"
        >
          <Share2 size={14} className="text-hacker-green" /> Generate AI Achievement Summary
        </button>

        <button
          onClick={handlePushToGitHub}
          disabled={isProcessing}
          className="bg-white hover:bg-gray-100 text-black font-bold px-6 py-2.5 rounded-lg text-xs font-mono flex items-center justify-center gap-2 transition-all shadow-md shrink-0"
        >
          {isProcessing ? <RefreshCw className="animate-spin" size={14} /> : <Github size={14} />}
          Commit Script to GitHub
        </button>
      </div>

      {actionStatus.text && (
        <div className={`p-2.5 rounded-lg text-xs flex items-center gap-2 ${
          actionStatus.isError ? "bg-red-500/10 border border-red-500/20 text-red-400" : "bg-hacker-green/10 border border-hacker-green/20 text-hacker-green"
        }`}>
          {actionStatus.isError ? <AlertCircle size={14} /> : <CheckCircle2 size={14} />}
          <span>{actionStatus.text}</span>
        </div>
      )}

      {/* Modal displaying AI Markdown summary and Dual Share targets */}
      {showLedgerModal && (
        <div className="fixed inset-0 bg-black/85 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-hacker-card border border-hacker-border w-full max-w-2xl rounded-xl p-6 flex flex-col gap-5 shadow-2xl">
            <div className="flex justify-between items-center border-b border-hacker-border pb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="text-hacker-amber" size={18} />
                <h3 className="font-bold text-white text-sm font-mono">AI-GENERATED DAILY RESEARCH LOG</h3>
              </div>
              <button
                onClick={() => {
                  setShowLedgerModal(false);
                  setTerminalLogs([]);
                }}
                className="text-xs text-hacker-muted hover:text-white font-mono"
              >
                [Close]
              </button>
            </div>

            {/* Markdown Summary block */}
            <div className="bg-hacker-dark border border-hacker-border rounded-lg p-4 max-h-[220px] overflow-y-auto font-sans text-xs flex flex-col gap-3">
              <pre className="font-mono text-[11px] text-gray-300 leading-relaxed whitespace-pre-wrap">
                {mdSummary}
              </pre>
            </div>

            {/* Simulated Live Terminal */}
            {terminalLogs.length > 0 && (
              <div className="bg-black border border-hacker-border rounded-lg p-3 max-h-[120px] overflow-y-auto font-mono text-[10px]">
                {terminalLogs.map((log, i) => (
                  <div key={i} className={log.includes("[+]") ? "text-hacker-green font-bold" : log.includes("[-]") ? "text-red-400" : "text-gray-400"}>
                    {log}
                  </div>
                ))}
              </div>
            )}

            {/* Actions Inside Modal */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 border-t border-hacker-border pt-4">
              <button
                onClick={handleCopyMarkdown}
                className="bg-hacker-dark hover:bg-hacker-border border border-hacker-border text-white text-xs font-mono py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
              >
                <Copy size={13} /> Copy Markdown Log
              </button>

              <button
                onClick={handlePushToGitHub}
                disabled={isProcessing}
                className="bg-white hover:bg-gray-100 text-black text-xs font-mono font-bold py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
              >
                <Github size={13} /> Commit to GitHub
              </button>

              <button
                onClick={handleLinkedInShare}
                className="bg-[#0077b5] hover:bg-[#006295] text-white text-xs font-mono py-2 rounded-lg flex items-center justify-center gap-1.5 transition-all"
              >
                <Linkedin size={13} /> Share on LinkedIn
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default SocialIntegrator;
